### PR TITLE
Implement Repayments Calculator using afb

### PR DESCRIPTION
**Pull request by Pareesh**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--nedbank--hlxsites.hlx.page/en/personal/borrow/personal-loans
- After: https://afb--nedbank--hlxsites.hlx.page/en/personal/borrow/personal-loans-afb

### CODE REVIEW

**Review by rofe — CHANGES_REQUESTED** [review]
- can you please fix the linting problems and rewrite the JS code to match the airbnb style?
- are all of these files really necessary to fulfil the calculator use case? if not, can the number be reduced to the minimum? if yes, the payload seems a bit enormous to me...

**Comment by jalagari** [comment]
> * can you please fix the linting problems and rewrite the JS code to match the airbnb style?
@Pareesh have fixed most of linting issue and will be updating PR.

> * are all of these files really necessary to fulfil the calculator use case? if not, can the number be reduced to the minimum? 
We have included entire Adaptive Form Block, which has all components (different types of input types like select, checkbox, radio, etc.) but  at runtime it will only load components used in Excel ( Form definition)

**Comment by trieloff** [comment]
> @Pareesh have fixed most of linting issue and will be updating PR.

```
$ npm run lint

✖ 9203 problems (9146 errors, 57 warnings)
  8094 errors and 0 warnings potentially fixable with the `--fix` option.
```

how many were there before?

**Comment by Pareesh** [comment]
Hi @trieloff ,
This PR currently doesn't include linting fix, waiting for them to merge in main afb block code https://github.com/adobe/adaptive-form-block/pull/4/files and then will update the code here to keep the code in sync.

cc : @jalagari
Thank you

**Comment by trieloff** [comment]
Looking at the repayment term slider in DOM gives me this:
```html
<div class="cmp-adaptiveform-range term">
    <div id="cmp-adaptiveform-textinput-npFwhawVY27" class="cmp-adaptiveform-textinput field2" data-cmp-visible="true" data-cmp-enabled="true" data-cmp-is="cmp-adaptiveform-textinput" data-cmp-valid="true" data-cmp-active="false">
        <label id="cmp-adaptiveform-textinput-npFwhawVY27-label" for="cmp-adaptiveform-textinput-npFwhawVY27" class="cmp-adaptiveform-textinput__label">What’s your preferred repayment term? *</label>
        <div class="cmp-adaptiveform-textinput__widget-wrapper">
            <span class="cmp-adaptiveform-textinput__widget-value" style="left: calc(14.285714%);">1 years</span>
            <input class="cmp-adaptiveform-textinput__widget" title="" name="term" placeholder="" required="" aria-label="What’s your preferred repayment term?" max="6" type="range" style="background-image: linear-gradient(to right, #78be20 16.666666666666664%, #C5C5C5 16.666666666666664%)">
                <span class="cmp-adaptiveform-textinput__widget-min">6 months</span>
                <span class="cmp-adaptiveform-textinput__widget-max">6 years</span>
            </div>
            <div id="cmp-adaptiveform-textinput-npFwhawVY27-errorMessage" class="cmp-adaptiveform-textinput__errorMessage"></div>
        </div>
    </div>
```

- why are there so many inline `style`s?
- why are the `id`s unreadable. What are they for?

**Comment by trieloff** [comment]
I expect there to be numerous other issues, so the question is if we want to fix them right here and them merge them back upstream (main development happens on the project) or vice versa. I'd prefer the main development to happen on the project.

**Comment by Pareesh** [comment]
>>> why are there so many inline styles?
Whenever range value is updated, we need to style the hover element to be positioned just above range slider thumb and slider background as well to match the current range slider thumb. 

We have already have a ticket to reduce this inline styling https://jira.corp.adobe.com/browse/CQ-4351316, will be moving to css variables.

**Comment by trieloff** [comment]
I think it would be easier to have the slider position `calc()`ed with `attr()`, so that the intrinsic values drive the display.

**Comment by Pareesh** [comment]
> why are the ids unreadable. What are they for?
@jalagari please revert about this query. AFAIK, the adaptiveform maintains a model for each form fields and assign a random id to each formfields if not present.

**Comment by jalagari** [comment]
> I'd prefer the main development to happen on the project.

We are doing main development at https://github.com/adobe/adaptive-form-block and updating customer repo. Recently we have add the NPM command to updating AdaptiveFormBlock based on version 

> why are the ids unreadable. What are they for?
AFB supporting binding and rules, Ids are used for binding of model and view similar to react-binding. Currently id are random string and there is plan to use field name as id but

**Comment by sdmcraft** [comment]
Some review feedback from my side..
1. Please review usage of `console.log/console.error` at several places in the PR. It's getting flagged by the linter.  For instances where you feel they are definitely needed (like error situations etc.) , you can mark them to be ignored via `// eslint-disable-next-line no-console`
2. We are using a limited number of components while the code seems to include a lot many. 
Here's what I see being used
image
Could we remove the ones from the code that are not needed? Similarly there might be other opportunities to remove unused code (like in `afb-formatters.js`, the date formatting logic is probably not needed).

1. Another observation when I compare the page load times with and without adaptive forms block is as follows:
With AFB 
image
Without AFB
image
We can check if the additional requests (20) can be reduced for AFB and also if the `Finish` (asynch load time) is increasing because of them.

**Comment by vdua** [comment]
Closing this PR and recreating a new one #48

**Pull request closed without merging**
