### PR TITLE
Footer layout tweaks

### PR DESCRIPTION
**Pull request by bosschaert**
* Stay safe link colour
* Link line thickness in mobile view
* Link spacing in desktop view

Fixes: #159
Fixes: #201

Test URLs:
- Before: https://main--nedbank--hlxsites.hlx.live
- After: https://issue-201--nedbank--hlxsites.hlx.live

### CODE REVIEW

**Comment by bosschaert** [comment]
The LHS result is most likely not related to this change. We can retry it later to see if we get a better score.

**Review by sdmcraft — APPROVED** [review]
Super minor nit-pick: The "Stay safe [Fraud awareness](https://personal.nedbank.co.za/home/fraud-awareness.html)" become multi-line in the ref site and the design spec (Invision) in mobile view but in our case, it remains a single line.

**Comment by bosschaert** [comment]
How can I see the mobile view in invision @sdmcraft ?

**Comment by sdmcraft** [comment]
> How can I see the mobile view in invision @sdmcraft ?

[Please use this link](https://nedbank.invisionapp.com/overview/RRB-COZAF-Personal-Landing-Page-Desktop-WEB-V1-MVP-SEP2021-FINAL-cl71d88kxi5cn01rvvv2h70am/screens?sortBy=1&sortOrder=1&viewLayout=1)

**Pull request merged**
