### PR TITLE
Header dropdown alignment, font and colours.

### PR DESCRIPTION
**Pull request by bosschaert**
Contributes to #111 fixes issue 1c and 1e.

Test URLs:
Before: https://main--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home
After: https://issue-111_1c--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home

### CODE REVIEW

**Comment by sdmcraft** [comment]
Looks like there's some undesirable side-effect on the `nav-tools`

Now
image

On main 
image

**Comment by bosschaert** [comment]
> Looks like there's some undesirable side-effect on the `nav-tools`

This is really strange. I can see the effect on https://issue-111_1c--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home but when I work on the branch locally via localhost:3000 it looks perfectly fine.

**Comment by bosschaert** [comment]
@sdmcraft all of the changes in this PR relate to the `secondary-nav` section which is not the section of the `nav-tools` so I can't understand how they could be related? Maybe this is some sort of anomaly in the site generation? As I mentioned above locally those search/login part render exactly like on main on my branch...

In any case one option could be to defer this issue until we're looking at #128 as we have do some work in that area then anyway?

**Comment by sdmcraft** [comment]
> In any case one option could be to defer this issue until we're looking at #128 as we have do some work in that area then anyway?

Yes. Perhaps an anomaly because of your branch being behind main..? I'd suggest updating your branch with `main` and push . If that doesn't fix, we can track is separately.

**Comment by bosschaert** [comment]
@sdm I merged out and now the difference is gone. Thanks!

**Pull request merged**
