### PR TITLE
Fix footer issues

### LINKED ISSUE #87: Address homepage styling issues
Reference page: https://personal.nedbank.co.za/home.html
Franklin page: https://main--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home

List of issues to be addressed

- Navbar background share cropped 
image

- Incorrect banner shade 
image

- Incorrect text font and style
image

- Align footer style
image
image

### PR DESCRIPTION
**Pull request by bosschaert**
Partly Fixes #87 

Test URLs:
- Before: https://main--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home
- After: https://issue-87_3--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home

### CODE REVIEW

**Comment by sdmcraft** [comment]
I see 2  Nedbank logos. Something to change in the footer word doc perhaps..?

image

**Comment by bosschaert** [comment]
> I see 2 Nedbank logos. Something to change in the footer word doc perhaps..?
> 
> image

Yes forgot to mention. Once this PR is merged the first one can be deleted from the worddoc. I thought it would make sense to wait with that until the PR is merged otherwise there would be no logo at all on main.

**Comment by sdmcraft** [comment]
Looks like footer text is left shifted 

Changed 
image

Expected
image

**Comment by bosschaert** [comment]
> Looks like footer text is left shifted

@sdmcraft that's actually true for the whole footer section (also the bits above the NEDBANK logo). I'll look into getting that closer.

**Comment by sdmcraft** [comment]
> Hi @sdmcraft I realigned the footer items, WDYT?

Umm..looks like the padding distorts the mobile view since we have borders defined for it. All the text in the footer seems squished.

image

image

**Comment by bosschaert** [comment]
Hi @sdmcraft with these changes the footer looks better now in the mobile view. I also changed the layout of the footer items so that they resize better. WDYT?

**Review by sdmcraft — APPROVED** [review]
It looks good. We can merge. One super minor comment, between a width of 1219px to 991px , look like the footer width becomes less to accommodate the text so it wraps. It works fine above and below these ranges. Maybe we can reduce the padding when the width goes below 1220px so that footer has more width.
But as I said, its super minor and we can take it up separately.

**Pull request merged**
